### ISSUE TITLE
FAILED: TimeWindow flow test fails occasionally

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka-stream-contrib#104]
[info] TimeWindow flow
[info] - should aggregate data for predefined amount of time *** FAILED *** (628 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(5), found OnNext(1)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:388)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:373)

**Comment by raboof** [comment]
It also sometimes timeouts: https://travis-ci.org/akka/akka-stream-contrib/jobs/253585538
```
[info] TimeWindowSpecAutoFusingOn:
[info] TimeWindow flow
[info] - should aggregate data for predefined amount of time *** FAILED *** (1 second, 325 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (200 milliseconds) during expectMsg while waiting for OnNext(5)
```
