### ISSUE TITLE
FAILED: A bunch of tests failed in ValveSpec 

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka-stream-contrib#106]
[info] ValveSpec:
[info] A closed valve
[info] - should emit only 3 elements into a sequence when the valve is switched to open (1 second, 14 milliseconds)
[info] - should emit only 5 elements when the valve is switched to open (485 milliseconds)
[info] - should emit only 3 elements when the valve is switch to open/close/open (317 milliseconds)
[info] - should return false when the valve is already closed (542 milliseconds)
[info] - should emit nothing when the source is empty (157 milliseconds)
[info] - should emit nothing when the source is failing (46 milliseconds)
[info] - should not pull elements again when opened and closed and re-opened *** FAILED *** (261 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 6 times, sleeping 15 milliseconds between each query. (ValveSpec.scala:171)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)

**Comment by manonthegithub** [comment]
Full logs [here](https://travis-ci.org/akka/akka-stream-contrib/jobs/252450701)

**Comment by manonthegithub** [comment]
also
[info] ValveSpec:
[info] A closed valve
[info] - should emit only 3 elements into a sequence when the valve is switched to open *** FAILED *** (1 second, 595 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 13 times, sleeping 15 milliseconds between each query. (ValveSpec.scala:44)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)

**Comment by manonthegithub** [comment]
and others.... Full logs [here](https://travis-ci.org/akka/akka-stream-contrib/jobs/252397160)

**Comment by raboof** [comment]
We use [org.scalatest.concurrent.Futures](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/concurrent/Futures.scala) here, which by default times out after 150 seconds.

I think it'd be fine to widen this timeout, as we don't expect to hit it in the happy case anyway.
