### ISSUE TITLE
LazyBroadcastHub

### ISSUE THREAD

**Issue by jroper** [akka/akka-stream-contrib#110]
Creating this issue here - maybe it's a good candidate for Akka streams proper, not sure. I've created a LazyBroadcastHub:

https://gist.github.com/jroper/4f8108f8fa00a7251919e08d4cf9eb71

The idea is that you have a source that you want to broadcast, but if there are no consumers, you want to shutdown the source, and start it up again when more consumers connect.

The specific use case that I wrote this for is reactive console, it connects to ConductR to receive bundle events, and you could have multiple clients connecting to consume these to render their UIs. But often there may be no clients connected, the effect of which would be that the hub will backpressure on ConductR, and an idle timeout flow in the middle will end up shutting the connection down, which will then be reconnected by a backoff supervisor, and so on.  So this is used to explicitly shut the connection down when not needed.

If you think it's worth including in akka-stream-contrib (or in akka-stream in some form), then I'll prepare a PR.

**Comment by johanandren** [comment]
I think it sounds interesting enough to include in Akka streams.

I wonder though if it couldn't be a simpler `Flow` stage, that only deals with canceling upstream on a back pressure timeout. That could then be combined with `BroadcastHub` rather than merging those two concerns in a single stage. Thinking that should make it useful in more contexts. Is it important that the shutting down is purely based on the number of downstream in the hub or would a timeout be good enough?

**Comment by jroper** [comment]
Timing out when there's no active pull I think is interesting.  Even if there's a hundred subscriptions to the hub, if the hub is back pressuring for more than the timeout, shutting down the stream until it pulls again is still a worthwhile thing to do.

**Comment by jroper** [comment]
This can almost be implemented already with a combination of `Flow.recoverWith` (or `RestartSource.withBackoff`), `Flow.idleTimeout` timeout, and `Source.lazily`:

def adhocSource[T](source: Source[T, _]): Source[T, _] = 
  Source.lazily(() => adhocSource(source)).idleTimeout(timeout).recoverWith { 
    case t: TimeoutException => adhocSource
  }
```

The reason this doesn't quite implement it is that `Flow.idleTimeout` will timeout when there is demand but the flow just isn't sending anything. So perhaps what we need is a `Flow.demandTimeout`. Then the combination of `Source.lazily` only materializing when there is demand, and `Flow.demandTimeout` shutting down and restarting when there's no demand will implement this.

I'll submit a PR for `FlowOps.demandTimeout` to Akka.

**Comment by jroper** [comment]
Oh, I just found `FlowOps.backpressureTimeout`, so as far as I'm concerned, this is already implemented by doing this:

```scala
def adhocSource[T](timeout: FiniteDuration, source: Source[T, _]): Source[T, _] = 
  Source.lazily(() => adhocSource(timeout, source)).backpressureTimeout(timeout).recoverWith { 
    case t: TimeoutException => adhocSource
  }
```
