### ISSUE TITLE
Facility to obtain the state of a valve's switch

### ISSUE THREAD

**Issue by zaharidichev** [akka/akka-stream-contrib#116]
Currently the `ValveSwitch` looks like 

```scala
sealed trait ValveSwitch {
  /**
   * Change the state of the valve
   *
   * @param mode expected mode to switch on
   * @return A future that completes with true if the mode did change and false if it already was in the requested mode
   */
  def flip(mode: SwitchMode): Future[Boolean]
}
```

I propose to add another method that will return a Future[SwitchMode] telling us what the state of the valve at the moment is. We have a strong case for using that in production.

**Comment by ktoso** [comment]
Feel free to submit a PR, sounds useful
