### ISSUE TITLE
PassThroughFlow limits the rate of the inner processingFlow

### ISSUE THREAD

**Issue by bchazalet** [akka/akka-stream-contrib#160]
### Versions used 

Akka stream version: 2.5.23

### Expected Behavior

`PassThroughFlow` should not limit the rate (or parallelism) of the inner processing flow. Or rather, the doc should warn about that behaviour.

### Actual Behavior

`PassThroughFlow` seems to limit the rate (or parallelism) of the `processingFlow` it takes as a parameter, and it's not obvious from the doc.

My scenario is the following. Say, I have some flow that has a degree of parallelism, although it maintains the order of messages. For example, this one:
``` scala
val innerFlow = Flow[String].mapAsync(5)(s =>  Future(s.toInt))
```

If I plug that into a `PassThroughFlow`, I expect multiple integers to be converted from String to Int in parallel. But that's not what happens. What happens is that only one message is processed at a time.

I understand that it's because of the way `Broadcast` and `Zip` work in the implementation (as explained [here](https://stackoverflow.com/questions/55219937/akka-streams-pass-through-flow-limiting-parallelism-throughput-of-processing-f). But it's definitely not obvious from the doc that it should be so.

Here's a full example:
```scala
val integers = List("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")

implicit val ec: ExecutionContext = ???

val fromStringToInt = (s: String) => Future {
  println(s"processing $s")
  Thread.sleep(100)
  s.toInt
}

val innerFlow = Flow[String]
  .mapAsync(5)(fromStringToInt)
  .wireTap(i => println(s"done with $i"))

val f = Source(integers)
  .via(PassThroughFlow(innerFlow))
  .runWith(Sink.seq)

f.onComplete {
  case Success(list) => println(list)
  case _ => // nothing
}

```

And what I see is that only one message is processed at a time:
```
processing 1
done with 1
processing 2
done with 2
processing 3
done with 3
processing 4
done with 4
processing 5
done with 5
processing 6
done with 6
processing 7
done with 7
processing 8
done with 8
processing 9
done with 9
processing 10
done with 10
Vector((1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7,7), (8,8), (9,9), (10,10))
```

**Comment by bchazalet** [comment]
Interestingly, if I add a buffer to the the implementation of the unprocessing branch of `PassThroughFlow` like this:

``` scala
  // broadcast.out(0) ~> zip.in0
  broadcast.out(0).buffer(parallelism, OverflowStrategy.backpressure) ~> zip.in0
  broadcast.out(1) ~> processingFlow ~> zip.in1
```

and obtain the behaviour that I was expecting:
```
processing 1
processing 3
processing 2
processing 4
processing 5
done with 1
done with 2
done with 3
processing 7
processing 6
done with 4
processing 8
done with 5
processing 9
processing 10
done with 6
done with 7
done with 8
done with 9
done with 10
Vector((1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7,7), (8,8), (9,9), (10,10))
```

**Comment by bchazalet** [comment]
actually, it's exactly the bug describe here https://github.com/akka/akka/issues/22975

**Comment by 2m** [comment]
The [`FlowWithContext` from `akka-stream` module](https://doc.akka.io/docs/akka/current/stream/operators/Flow/asFlowWithContext.html#flow-asflowwithcontext), supersedes `PassThroughFlow` from this repository.

Does `FlowWithContext` fit your usecase?

**Comment by bchazalet** [comment]
I came across `FlowWithContext` while I was researching my problem and first thought this is exactly what I wanted. After playing a bit with it, I'm not sure it's a good fit, as usually my inner flows need access to the context as input, but as far as I understand the context is completely hidden from that inner flow. 

Thanks for the suggestion though, and feel free to close the issue if it's not relevant.

**Comment by 2m** [comment]
Yes, context is hidden. If some part of the inner flow needs the context, you can drop from `FlowWithContext` to a regular `Flow` that emits pairs of element and context.

I am going to close this, and create a ticket for removal of `PassThroughFlow` from this repo.
