### ISSUE TITLE
Why no more releases?

### ISSUE THREAD

**Issue by lostiniceland** [akka/akka-stream-contrib#187]
This repo is still active, and even the CI-pipeline has just been adjusted. Why are there no more releases? It is just another CI run I guess, so no real overhead.

The benefit of having a binary release is that I do not have the source in my codebase.

As mentioned here https://discuss.lightbend.com/t/ideas-on-how-to-implement-a-latency-monitor-which-wraps-a-flow/5714/7 this repo provided valuable additions for some edge-cases.

Personally: I am in need of a new release due to the merge from September.

**Comment by ennru** [comment]
Thank you for your question.
We in the Akka team can't maintain this repository with the level of quality we provide for what we release as libraries. 
That is why we leave it for you as the user to copy and paste the parts you need. Most users will only need a single functionality illustrated in this repo.
