### ISSUE TITLE
Move Accumulate and LastElement from hseeberger/akka-commons-streams here

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-stream-contrib#3]
- [Accumulate](https://github.com/hseeberger/commons-akka/blob/master/commons-akka-stream/src/main/scala/de/heikoseeberger/commons/akka/stream/Accumulate.scala#L48): This stage emits folded values like `scan`, but the first element emitted is not the zero value but the result of applying the given function to the given zero value and the first pushed element.
- [LastElement](https://github.com/hseeberger/commons-akka/blob/master/commons-akka-stream/src/main/scala/de/heikoseeberger/commons/akka/stream/LastElement.scala#L43): This stage materializes to the last element pushed before upstream completion, if any, thereby recovering from any failure. Pushed elements are just passed along.

**Comment by hseeberger** [comment]
Akka team, suggestions for renaming `Accumulate` are appreciated.

**Comment by patriknw** [comment]
sounds good, looking forward to the PR

**Comment by drewhk** [comment]
Almost anything goes in this repo, so feel free to add these. I think we will still need JavaDSL though?

**Comment by hseeberger** [comment]
@drewhk, there's no Scala DSL, just these two stages implementing GraphStage. How would a Java DSL look like?

**Comment by drewhk** [comment]
I mean, it should be usable from Java. Stages I think are fine.

**Comment by hseeberger** [comment]
Aye.
@drewhk, @patriknw, what would be a good package name? `akka.stream.contrib`?

**Comment by patriknw** [comment]
akka.stream.contrib sounds good to me

**Comment by drewhk** [comment]
I guess we will figure out in more detail the package structure below that. I guess there will be a `scaladsl` and `javadsl` subpackage for stuff where it matters.
