### ISSUE TITLE
Add UnfoldFlow Source generator

### ISSUE THREAD

**Issue by hochgi** [akka/akka-stream-contrib#32]
a pattern I see comes up often in my code, is "unfolding" from flow.
I'll start with a pretty simple (yet useful) example:

consider Elasticsearch's [scroll API](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/scroll.html). using it, you can traverse large amounts of data. So using the existing API, one might come up with something similar to (pseudo code - not real http client):

```scala
Source.unfoldAsync(initialScrollId) { scrollId =>
  val res: Future[HttpResponse] = httpClient.request(buildRequestFromId(scrollId))
  res.map { r =>
    val data = extractDataFrom(r)
    val next =  extractNextScrollIdFrom(r)
    if(data.isEmpty) None
    else Some(data -> next)
  }
}
```

well, since we are using streams, it might be much more efficient to use `akka-http`s connection pool flows. only problem, we don't want redundant sub streams materialization, we might be using with `Source.unfoldAsync`:

```scala
//BAD EXAMPLE
Source.single(buildRequestFromId(scrollId)).via(connectionPoolFlow).runWith(Sink.head)
```

So, I'm suggesting to create an unfolding source from a flow, by building a graph similar to:

![Source.unfoldFlow](http://i.imgur.com/MOmBWLJ.png)

API should be pretty straight forward:
```scala
def unfoldFlow[A,B,C,M](seed: A, flow: Flow[A,B,M])(unfoldWith: B => Option[(A,C)]): Source[C,M]
```

If you guys think it's useful, I'd be happy to create a PR for this.
and, IMO, this is something that could eventually migrate to the main streams module.

**Comment by hochgi** [comment]
some concerns: 
- given flow might output more elements than what it takes for input.
- given flow might output less elements than what it takes for input.
- given flow might ask for more elements before emitting old ones.

possible handling of these cases:
- doesn't matter if more elements are coming out. we can decide the last element is the one used to create the next output elements. or the first received after a push to the flow, or we might generalize it and also accept a handling strategy.
- if less elements are outputted, than we can just re-send the last element again. if the flow will stay stuck, not emitting anything, we can consider this as the user fault. also, we might solve this with (an overkill solution IMHO) by getting a function `B => Option[(Source[A,_],C)]`, and emit different `A` elements to the flows when it asks for more.

**Comment by hochgi** [comment]
A simpler signature would be:
```scala
def unfoldFlow[S, E, M](seed: S)(flow: Graph[FlowShape[S, (S,E)], M]): Source[E, M]
```
There's no need for optional tuple, since given flow can just complete instead of emitting `None`.
But, It might be more flexible/easier for some scenarios, to use the original suggestion.
I'm thinking about having 2 separate APIs: `unfoldFlowWith` & `unfoldFlow`.

**Comment by drewhk** [comment]
Sorry for the late reply. This indeed looks like a great idea!

As for "given flow might output more elements than what it takes for input" one can always put a buffer after the flow, possibly setting it to OverflowStrategy.fail
