### ISSUE TITLE
Directory watch - added, changed, deleted files as events

### ISSUE THREAD

**Issue by johanandren** [akka/akka-stream-contrib#35]
Idea for a new source, I have one lying around on my computer since earlier and there was discussions on akka/akka about such a source.

I'm thinking `Source[(Path, ChangeType), SomeWayToCancel]` or possibly skip that `SomeWayToCancel` since it can be achieved by combining with a `KillSwitch`

**Comment by joearasin** [comment]
It's a bit of a hack, but to play around with other pieces of the system and punt the innards of this to later, I used:

```
  val monitor = RxMonitor()
  val observable: Observable[EventAtPath] = monitor.observable
  val publisher = RxReactiveStreams.toPublisher(JavaConversions.toJavaObservable(observable))
  val eventSource: Source[EventAtPath, NotUsed] = Source.fromPublisher(publisher)
  // Run things 
  monitor.registerPath(ENTRY_MODIFY, "/path/to/whatever")
```
using https://github.com/lloydmeta/schwatcher with RxReactiveStreams

**Comment by johanandren** [comment]
We also discussed pulling in https://github.com/pathikrit/better-files and use their actor based watch. But I think I'll stick to using the JDK provided `WatchService` (https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#newWatchService--). It's a pretty horrible interface, but it's 0-dependencies so that is a nice thing. It should be using native OS facilities on some platforms AFAIR.
