### ISSUE TITLE
Build and release against Scala 2.12

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-stream-contrib#67]

**Comment by samueltardieu** [comment]
and maybe do that with a 0.5 version number to include mqtt authentication.

**Comment by hseeberger** [comment]
Now that Akka HTTP 10 is published (as RC2) it would be really really good to see this library get released against 2.12.

**Comment by hseeberger** [comment]
The build should be in shape, see #77.

**Comment by patriknw** [comment]
yes, I'll do that today

**Comment by hseeberger** [comment]
Great, thanks!

**Comment by patriknw** [comment]
it's on the way to maven central now

**Comment by hseeberger** [comment]
Great!
