### ISSUE TITLE
Question on how cassandra connector works

### ISSUE THREAD

**Issue by hardvain** [akka/akka-stream-contrib#68]
I see that the custom graph stage logic polls cassandra asynchronously and gets data. Wont that cause network call overload?

**Comment by atamborrino** [comment]
The Akka Stream model implies that only one async call will be "in-flight" at a given time, and moreover Cassandra's ResultSet is using page to get multiple rows in one call, so I don't think there is an issue here.

**Comment by hardvain** [comment]
@atamborrino So you are telling that since the results are paginated, the number of network calls will be less and hence not much of a problem?

**Comment by atamborrino** [comment]
Yes. The whole thing is just a trade-off between the amount of memory needed in your program and the number of IO calls to make. If you want less IO calls, increase the Cassandra statement fetch size, but you program will need more memory to buffer larger row pages.

**Comment by hardvain** [comment]
@atamborrino Thanks. It clarifies my doubt.
