### ISSUE TITLE
AWS S3 integration

### ISSUE THREAD

**Issue by agolubev** [akka/akka-stream-contrib#75]
Just passed AWS certification and going to do some AWS integration. Perhaps S3 is the simplest one so going to start from this. 
Is it still hot topic?

**Comment by patriknw** [comment]
@agolubev That is very interesting, and hot. We will create a separate Alpakka repository any day now.

You can also take a look at
https://github.com/MfgLabs/akka-stream-extensions
https://github.com/MfgLabs/commons-aws

**Comment by ktoso** [comment]
Would be great to get in touch with them, I know they wanted to contribute as well.

**Comment by 2m** [comment]
@agolubev that is very welcome. I will open S3 integration ticket on the Alpakka repository.
