### ISSUE TITLE
contrib sub-project depends on akka-stream-testkit in Compile configuration

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-stream-contrib#82]
It looks like this is necessary for `Coroner`, but nevertheless I think it's a no-go to pull test libraries into `Compile` configuration. Now every project depending on akka-stream-contrib, like akka-sse, has a `Compile` dependency on akka-stream-contrib.

**Comment by hseeberger** [comment]
BTW, this has been introduced in commit d24c080e.

**Comment by patriknw** [comment]
I agree, that is wrong. Looks like we need a akka-stream-contrib-testkit

**Comment by patriknw** [comment]
Or set it to provided

**Comment by hseeberger** [comment]
Set what to provided?

**Comment by hseeberger** [comment]
Maybe we need an akka-stream-testkit-contrib instead of akka-stream-contrib-testkit?

**Comment by hseeberger** [comment]
Should we revert the commit that introduced this bug and make a new release?

**Comment by patriknw** [comment]
I think it's easiest to set the akka-stream-testkit dependency to "provided". That means that user needs to add that dependency if the use the Coroner

**Comment by hseeberger** [comment]
I agree, that's the easiest, i.e. quickest, fix. On the long run that looks a little fishy to me.
Should I create a PR with the "provided" fix? If so, could you release a 0.5.1 soonish?

**Comment by hseeberger** [comment]
Here you are: https://github.com/akka/akka-stream-contrib/pull/83

**Comment by hseeberger** [comment]
Thanks!
