### ISSUE TITLE
DelayFlow stage with flexible delay management

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka-stream-contrib#89]
I needed flexible mechanism to make delay in stream under certain circumstances (for example if http server goes down not to oveload it with redundant requests, delay for some time after receiving some number of 500 error codes in a row) and thought that it can be useful to others. I'll submit PR with my implementation soon. It will be great, if you'll decide that it would be useful.

**Comment by 2m** [comment]
Fixed in #90
