### ISSUE TITLE
Sources for requesting from paged APIs

### ISSUE THREAD

**Issue by dpfeiffer** [akka/akka-stream-contrib#93]
When streaming items from paged APIs I find myself often using unfoldAsync based implementations to solve the issue. Would a GraphStage based approach fit in here?

A possible implementation would support 3 different kinds of pagination:
* Limit/Offset based
* Page based
* Next Link based (Like AWS does 

What do you think?

**Comment by ktoso** [comment]
Sounds interesting, do you have an idea how the API would look like?

**Comment by johanandren** [comment]
What would it give that `Source.unfoldAsyncResource` does not? Could it just be sugar on top of that stage, or maybe it's something we could put in the streams cookbook docs?

**Comment by dpfeiffer** [comment]
I would have to try around a little bit but in the end it would lead to something like this which would be mostly sugar on top of `Source.unfoldAsync`:

```scala
case class Item(...)
case class Page[T](next: Option[Int], items: Seq[T])

object PagedSource{
  def apply[T](f: Int => Future[Page[T]], firstPage: Int = 0) = ...
}

val f: Int => Future[Page[Item]] = ...
val s: Source[Item, NotUsed] = PagedSource(f)
```
So the things it would do:
* Provide case classes for paging
* flattening the pages to a `Source` of `Item`

**Comment by johanandren** [comment]
That is pretty neat :)
